---
name: nfs4

stemcells:
  - alias:   default
    os:      ubuntu-xenial
    version: latest

instance_groups:
  - name: server
    instances: 1
    vm_type: default
    persistent_disk: 10_240
    stemcell: default
    azs: [z1]
    networks:
      - name: default
    jobs:
      - name: nfs-server
        release: nfs
        properties:
          nfsd_arguments:   -N 2 -N 3 -V 4
          mountd_arguments: -N 2 -N 3 -V 4
          exports:
            - path: volume1

      - name: nfs-client
        release: nfs
        properties:
          mounts:
            - server: 127.0.0.1
              remote: volume1
              local:  /tmp/v1

  - name: client
    instances: 1
    vm_type: default
    persistent_disk: 10_240
    stemcell: default
    azs: [z1]
    networks:
      - name: default
    jobs:
      - name: nfs-client
        release: nfs

update:
  canaries: 1
  max_in_flight: 50
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

releases:
  - name:    nfs
    version: 1.0.2
    url:     https://github.com/jhunt/nfs-boshrelease/releases/download/v1.0.2/nfs-1.0.2.tgz
    sha1:    2181b1d78b9f98d91f8987504c4d0a8d858caa98
